using System.Collections;
using System.Collections.Generic;
using UnityEngine;
using UnityEngine.InputSystem;

public class PlayerController : MonoBehaviour
{
    //This is the input actions generated by Unity's new input system. I put it in just because it already has the Joystick stuff we would use, so we can make it work with it if we want
    CastleCrashers controls;
    CharacterController controller;

    [System.NonSerialized]
    public Vector2 movement_input;

    private void Awake()
    {
        controls = new CastleCrashers();
        controller = GetComponent<CharacterController>();

        controls.Player.Move.performed += ctx => movement_input = ctx.ReadValue<Vector2>();
        controls.Player.Move.canceled += ctx => movement_input = Vector2.zero;
        controls.Player.Attack.started += ctx => Attack();
    }

    private void FixedUpdate()
    {
        HandleMovement();
    }
    private void Attack()
    {

    }

    private void HandleMovement()
    {
        Vector3 input_direction = new Vector3(movement_input.x, movement_input.y, 0.0f);

        controller.Move(input_direction * Time.deltaTime);
    }
}
